// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/prime.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrimeService_GetPreParams_FullMethodName  = "/prime.PrimeService/GetPreParams"
	PrimeService_HealthCheck_FullMethodName   = "/prime.PrimeService/HealthCheck"
	PrimeService_GetPoolStatus_FullMethodName = "/prime.PrimeService/GetPoolStatus"
)

// PrimeServiceClient is the client API for PrimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimeServiceClient interface {
	// Get PreParamsData for ECDSA DKG (single or batch)
	GetPreParams(ctx context.Context, in *GetPreParamsRequest, opts ...grpc.CallOption) (*GetPreParamsResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	// Get pool status
	GetPoolStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PoolStatus, error)
}

type primeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeServiceClient(cc grpc.ClientConnInterface) PrimeServiceClient {
	return &primeServiceClient{cc}
}

func (c *primeServiceClient) GetPreParams(ctx context.Context, in *GetPreParamsRequest, opts ...grpc.CallOption) (*GetPreParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPreParamsResponse)
	err := c.cc.Invoke(ctx, PrimeService_GetPreParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primeServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, PrimeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primeServiceClient) GetPoolStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PoolStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolStatus)
	err := c.cc.Invoke(ctx, PrimeService_GetPoolStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimeServiceServer is the server API for PrimeService service.
// All implementations must embed UnimplementedPrimeServiceServer
// for forward compatibility.
type PrimeServiceServer interface {
	// Get PreParamsData for ECDSA DKG (single or batch)
	GetPreParams(context.Context, *GetPreParamsRequest) (*GetPreParamsResponse, error)
	// Health check
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	// Get pool status
	GetPoolStatus(context.Context, *Empty) (*PoolStatus, error)
	mustEmbedUnimplementedPrimeServiceServer()
}

// UnimplementedPrimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimeServiceServer struct{}

func (UnimplementedPrimeServiceServer) GetPreParams(context.Context, *GetPreParamsRequest) (*GetPreParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreParams not implemented")
}
func (UnimplementedPrimeServiceServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPrimeServiceServer) GetPoolStatus(context.Context, *Empty) (*PoolStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolStatus not implemented")
}
func (UnimplementedPrimeServiceServer) mustEmbedUnimplementedPrimeServiceServer() {}
func (UnimplementedPrimeServiceServer) testEmbeddedByValue()                      {}

// UnsafePrimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimeServiceServer will
// result in compilation errors.
type UnsafePrimeServiceServer interface {
	mustEmbedUnimplementedPrimeServiceServer()
}

func RegisterPrimeServiceServer(s grpc.ServiceRegistrar, srv PrimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimeService_ServiceDesc, srv)
}

func _PrimeService_GetPreParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeServiceServer).GetPreParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimeService_GetPreParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeServiceServer).GetPreParams(ctx, req.(*GetPreParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimeService_GetPoolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeServiceServer).GetPoolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimeService_GetPoolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeServiceServer).GetPoolStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimeService_ServiceDesc is the grpc.ServiceDesc for PrimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeService",
	HandlerType: (*PrimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPreParams",
			Handler:    _PrimeService_GetPreParams_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PrimeService_HealthCheck_Handler,
		},
		{
			MethodName: "GetPoolStatus",
			Handler:    _PrimeService_GetPoolStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prime.proto",
}
