// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/prime.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_prime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{0}
}

// PreParamsData message for complete parameters
type PreParamsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paillier key components
	PaillierP       []byte `protobuf:"bytes,1,opt,name=paillier_p,json=paillierP,proto3" json:"paillier_p,omitempty"`
	PaillierQ       []byte `protobuf:"bytes,2,opt,name=paillier_q,json=paillierQ,proto3" json:"paillier_q,omitempty"`
	PaillierN       []byte `protobuf:"bytes,3,opt,name=paillier_n,json=paillierN,proto3" json:"paillier_n,omitempty"`
	PaillierPhiN    []byte `protobuf:"bytes,4,opt,name=paillier_phi_n,json=paillierPhiN,proto3" json:"paillier_phi_n,omitempty"`
	PaillierLambdaN []byte `protobuf:"bytes,5,opt,name=paillier_lambda_n,json=paillierLambdaN,proto3" json:"paillier_lambda_n,omitempty"`
	// Additional parameters for ECDSA
	NTildei       []byte `protobuf:"bytes,6,opt,name=n_tildei,json=nTildei,proto3" json:"n_tildei,omitempty"`
	H1I           []byte `protobuf:"bytes,7,opt,name=h1i,proto3" json:"h1i,omitempty"`
	H2I           []byte `protobuf:"bytes,8,opt,name=h2i,proto3" json:"h2i,omitempty"`
	Alpha         []byte `protobuf:"bytes,9,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta          []byte `protobuf:"bytes,10,opt,name=beta,proto3" json:"beta,omitempty"`
	P             []byte `protobuf:"bytes,11,opt,name=p,proto3" json:"p,omitempty"`                                         // safe prime for NTildei
	Q             []byte `protobuf:"bytes,12,opt,name=q,proto3" json:"q,omitempty"`                                         // safe prime for NTildei
	GeneratedAt   int64  `protobuf:"varint,13,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreParamsData) Reset() {
	*x = PreParamsData{}
	mi := &file_proto_prime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreParamsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreParamsData) ProtoMessage() {}

func (x *PreParamsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreParamsData.ProtoReflect.Descriptor instead.
func (*PreParamsData) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{1}
}

func (x *PreParamsData) GetPaillierP() []byte {
	if x != nil {
		return x.PaillierP
	}
	return nil
}

func (x *PreParamsData) GetPaillierQ() []byte {
	if x != nil {
		return x.PaillierQ
	}
	return nil
}

func (x *PreParamsData) GetPaillierN() []byte {
	if x != nil {
		return x.PaillierN
	}
	return nil
}

func (x *PreParamsData) GetPaillierPhiN() []byte {
	if x != nil {
		return x.PaillierPhiN
	}
	return nil
}

func (x *PreParamsData) GetPaillierLambdaN() []byte {
	if x != nil {
		return x.PaillierLambdaN
	}
	return nil
}

func (x *PreParamsData) GetNTildei() []byte {
	if x != nil {
		return x.NTildei
	}
	return nil
}

func (x *PreParamsData) GetH1I() []byte {
	if x != nil {
		return x.H1I
	}
	return nil
}

func (x *PreParamsData) GetH2I() []byte {
	if x != nil {
		return x.H2I
	}
	return nil
}

func (x *PreParamsData) GetAlpha() []byte {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *PreParamsData) GetBeta() []byte {
	if x != nil {
		return x.Beta
	}
	return nil
}

func (x *PreParamsData) GetP() []byte {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *PreParamsData) GetQ() []byte {
	if x != nil {
		return x.Q
	}
	return nil
}

func (x *PreParamsData) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

type GetPreParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // Number of PreParams to return (default 1 if not specified)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreParamsRequest) Reset() {
	*x = GetPreParamsRequest{}
	mi := &file_proto_prime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreParamsRequest) ProtoMessage() {}

func (x *GetPreParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreParamsRequest.ProtoReflect.Descriptor instead.
func (*GetPreParamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreParamsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetPreParamsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Params           []*PreParamsData       `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"` // Returns 1 or more PreParamsData
	GenerationTimeMs int64                  `protobuf:"varint,2,opt,name=generation_time_ms,json=generationTimeMs,proto3" json:"generation_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPreParamsResponse) Reset() {
	*x = GetPreParamsResponse{}
	mi := &file_proto_prime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreParamsResponse) ProtoMessage() {}

func (x *GetPreParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreParamsResponse.ProtoReflect.Descriptor instead.
func (*GetPreParamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreParamsResponse) GetParams() []*PreParamsData {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetPreParamsResponse) GetGenerationTimeMs() int64 {
	if x != nil {
		return x.GenerationTimeMs
	}
	return 0
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_prime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{4}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type PoolStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pools          map[string]*PoolInfo   `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key: "1024_true" etc.
	TotalGenerated int64                  `protobuf:"varint,2,opt,name=total_generated,json=totalGenerated,proto3" json:"total_generated,omitempty"`                                  // Total params generated since start
	TotalServed    int64                  `protobuf:"varint,3,opt,name=total_served,json=totalServed,proto3" json:"total_served,omitempty"`                                           // Total params served to clients
	GenerationRate float64                `protobuf:"fixed64,4,opt,name=generation_rate,json=generationRate,proto3" json:"generation_rate,omitempty"`                                 // Params per second
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PoolStatus) Reset() {
	*x = PoolStatus{}
	mi := &file_proto_prime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatus) ProtoMessage() {}

func (x *PoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatus.ProtoReflect.Descriptor instead.
func (*PoolStatus) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{5}
}

func (x *PoolStatus) GetPools() map[string]*PoolInfo {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *PoolStatus) GetTotalGenerated() int64 {
	if x != nil {
		return x.TotalGenerated
	}
	return 0
}

func (x *PoolStatus) GetTotalServed() int64 {
	if x != nil {
		return x.TotalServed
	}
	return 0
}

func (x *PoolStatus) GetGenerationRate() float64 {
	if x != nil {
		return x.GenerationRate
	}
	return 0
}

type PoolInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Bits           uint32                 `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
	SafePrime      bool                   `protobuf:"varint,2,opt,name=safe_prime,json=safePrime,proto3" json:"safe_prime,omitempty"`
	Available      uint32                 `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`                                   // Current pool size
	TargetSize     uint32                 `protobuf:"varint,4,opt,name=target_size,json=targetSize,proto3" json:"target_size,omitempty"`               // Target pool size
	Generating     uint32                 `protobuf:"varint,5,opt,name=generating,proto3" json:"generating,omitempty"`                                 // Currently being generated
	LastRefillTime int64                  `protobuf:"varint,6,opt,name=last_refill_time,json=lastRefillTime,proto3" json:"last_refill_time,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PoolInfo) Reset() {
	*x = PoolInfo{}
	mi := &file_proto_prime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolInfo) ProtoMessage() {}

func (x *PoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolInfo.ProtoReflect.Descriptor instead.
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return file_proto_prime_proto_rawDescGZIP(), []int{6}
}

func (x *PoolInfo) GetBits() uint32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *PoolInfo) GetSafePrime() bool {
	if x != nil {
		return x.SafePrime
	}
	return false
}

func (x *PoolInfo) GetAvailable() uint32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *PoolInfo) GetTargetSize() uint32 {
	if x != nil {
		return x.TargetSize
	}
	return 0
}

func (x *PoolInfo) GetGenerating() uint32 {
	if x != nil {
		return x.Generating
	}
	return 0
}

func (x *PoolInfo) GetLastRefillTime() int64 {
	if x != nil {
		return x.LastRefillTime
	}
	return 0
}

var File_proto_prime_proto protoreflect.FileDescriptor

const file_proto_prime_proto_rawDesc = "" +
	"\n" +
	"\x11proto/prime.proto\x12\x05prime\"\a\n" +
	"\x05Empty\"\xe6\x02\n" +
	"\rPreParamsData\x12\x1d\n" +
	"\n" +
	"paillier_p\x18\x01 \x01(\fR\tpaillierP\x12\x1d\n" +
	"\n" +
	"paillier_q\x18\x02 \x01(\fR\tpaillierQ\x12\x1d\n" +
	"\n" +
	"paillier_n\x18\x03 \x01(\fR\tpaillierN\x12$\n" +
	"\x0epaillier_phi_n\x18\x04 \x01(\fR\fpaillierPhiN\x12*\n" +
	"\x11paillier_lambda_n\x18\x05 \x01(\fR\x0fpaillierLambdaN\x12\x19\n" +
	"\bn_tildei\x18\x06 \x01(\fR\anTildei\x12\x10\n" +
	"\x03h1i\x18\a \x01(\fR\x03h1i\x12\x10\n" +
	"\x03h2i\x18\b \x01(\fR\x03h2i\x12\x14\n" +
	"\x05alpha\x18\t \x01(\fR\x05alpha\x12\x12\n" +
	"\x04beta\x18\n" +
	" \x01(\fR\x04beta\x12\f\n" +
	"\x01p\x18\v \x01(\fR\x01p\x12\f\n" +
	"\x01q\x18\f \x01(\fR\x01q\x12!\n" +
	"\fgenerated_at\x18\r \x01(\x03R\vgeneratedAt\"+\n" +
	"\x13GetPreParamsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"r\n" +
	"\x14GetPreParamsResponse\x12,\n" +
	"\x06params\x18\x01 \x03(\v2\x14.prime.PreParamsDataR\x06params\x12,\n" +
	"\x12generation_time_ms\x18\x02 \x01(\x03R\x10generationTimeMs\"i\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x80\x02\n" +
	"\n" +
	"PoolStatus\x122\n" +
	"\x05pools\x18\x01 \x03(\v2\x1c.prime.PoolStatus.PoolsEntryR\x05pools\x12'\n" +
	"\x0ftotal_generated\x18\x02 \x01(\x03R\x0etotalGenerated\x12!\n" +
	"\ftotal_served\x18\x03 \x01(\x03R\vtotalServed\x12'\n" +
	"\x0fgeneration_rate\x18\x04 \x01(\x01R\x0egenerationRate\x1aI\n" +
	"\n" +
	"PoolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.prime.PoolInfoR\x05value:\x028\x01\"\xc6\x01\n" +
	"\bPoolInfo\x12\x12\n" +
	"\x04bits\x18\x01 \x01(\rR\x04bits\x12\x1d\n" +
	"\n" +
	"safe_prime\x18\x02 \x01(\bR\tsafePrime\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\rR\tavailable\x12\x1f\n" +
	"\vtarget_size\x18\x04 \x01(\rR\n" +
	"targetSize\x12\x1e\n" +
	"\n" +
	"generating\x18\x05 \x01(\rR\n" +
	"generating\x12(\n" +
	"\x10last_refill_time\x18\x06 \x01(\x03R\x0elastRefillTime2\xbb\x01\n" +
	"\fPrimeService\x12G\n" +
	"\fGetPreParams\x12\x1a.prime.GetPreParamsRequest\x1a\x1b.prime.GetPreParamsResponse\x120\n" +
	"\vHealthCheck\x12\f.prime.Empty\x1a\x13.prime.HealthStatus\x120\n" +
	"\rGetPoolStatus\x12\f.prime.Empty\x1a\x11.prime.PoolStatusB*Z(github.com/TEENet-io/prime-service/protob\x06proto3"

var (
	file_proto_prime_proto_rawDescOnce sync.Once
	file_proto_prime_proto_rawDescData []byte
)

func file_proto_prime_proto_rawDescGZIP() []byte {
	file_proto_prime_proto_rawDescOnce.Do(func() {
		file_proto_prime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prime_proto_rawDesc), len(file_proto_prime_proto_rawDesc)))
	})
	return file_proto_prime_proto_rawDescData
}

var file_proto_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_prime_proto_goTypes = []any{
	(*Empty)(nil),                // 0: prime.Empty
	(*PreParamsData)(nil),        // 1: prime.PreParamsData
	(*GetPreParamsRequest)(nil),  // 2: prime.GetPreParamsRequest
	(*GetPreParamsResponse)(nil), // 3: prime.GetPreParamsResponse
	(*HealthStatus)(nil),         // 4: prime.HealthStatus
	(*PoolStatus)(nil),           // 5: prime.PoolStatus
	(*PoolInfo)(nil),             // 6: prime.PoolInfo
	nil,                          // 7: prime.PoolStatus.PoolsEntry
}
var file_proto_prime_proto_depIdxs = []int32{
	1, // 0: prime.GetPreParamsResponse.params:type_name -> prime.PreParamsData
	7, // 1: prime.PoolStatus.pools:type_name -> prime.PoolStatus.PoolsEntry
	6, // 2: prime.PoolStatus.PoolsEntry.value:type_name -> prime.PoolInfo
	2, // 3: prime.PrimeService.GetPreParams:input_type -> prime.GetPreParamsRequest
	0, // 4: prime.PrimeService.HealthCheck:input_type -> prime.Empty
	0, // 5: prime.PrimeService.GetPoolStatus:input_type -> prime.Empty
	3, // 6: prime.PrimeService.GetPreParams:output_type -> prime.GetPreParamsResponse
	4, // 7: prime.PrimeService.HealthCheck:output_type -> prime.HealthStatus
	5, // 8: prime.PrimeService.GetPoolStatus:output_type -> prime.PoolStatus
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_prime_proto_init() }
func file_proto_prime_proto_init() {
	if File_proto_prime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prime_proto_rawDesc), len(file_proto_prime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_prime_proto_goTypes,
		DependencyIndexes: file_proto_prime_proto_depIdxs,
		MessageInfos:      file_proto_prime_proto_msgTypes,
	}.Build()
	File_proto_prime_proto = out.File
	file_proto_prime_proto_goTypes = nil
	file_proto_prime_proto_depIdxs = nil
}
